src/objects/API_Log__c.object
<CustomObject>
    <fields>
        <fullName>Api_Method__c</fullName>
        <label>Api Method</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Date__c</fullName>
        <label>Create Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Endpiont__c</fullName>
        <label>Endpiont</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <label>Object Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>API Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/LogBuilder.cls
/**
 * Created by dominikbarchanski on 27/05/2022.
 */

public with sharing class LogBuilder {
    public static API_Log__c record ;
    public static void createLog(String objectId, HttpRequest request, HttpResponse response) {
        record= LogBuilder.getBuilder()
                .setEndpoint(request.getEndpoint())
                .setStatusCode(response.getStatusCode())
                .setRequestBody(request.getBody())
                .setResponseBody(response.getBody())
                .setRequest(request.toString())
                .setCreateDate()
                .setApiMethod((request.getMethod()))
                .setObjectId(objectId)
                .save()
                .getRecord();

    }
    public static Builder getBuilder() {
        return new Builder();
    }

    public class Builder {
        public API_Log__c record;

        public Builder() {
            record = new API_Log__c();
        }

        public Builder setEndpoint(String endpoint) {
            record.Endpiont__c = endpoint;
            return this;
        }
        public Builder setRequest(String request) {
            record.Request__c = request;
            return this;
        }
        public Builder setApiMethod(String method){
            record.Api_Method__c = method;
            return this;
        }
        public Builder setObjectId(String Id){
            record.Object_Id__c = Id;
            return this;
        }
        public Builder setStatusCode(Decimal statusCode) {
            record.Status_Code__c = statusCode;
            return this;
        }
        public Builder setCreateDate(){
            record.Create_Date__c = Date.today();
            return this;
        }

        public Builder setRequestBody(String requestBody) {
            record.Request_Body__c = requestBody;
            return this;
        }

        public Builder setResponseBody(String responseBody) {
            record.Response_Body__c = responseBody;
            return  this;
        }

        public Builder save() {
            insert record;
            return  this;
        }

        public API_Log__c getRecord() {
            return record;
        }
    }
}