src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <label>Brands</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>carBrand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Horsepower__c</fullName>
        <label>Horsepower</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Photo__c</fullName>
        <label>Main Photo</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategy__c.object
<CustomObject>
    <fields>
        <fullName>Product2id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product2id</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Strategys</relationshipLabel>
        <relationshipName>Strategys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Strategy_Name__c</fullName>
        <label>Strategy Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Strategy_price__c</fullName>
        <label>Strategy price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Aura_dmlOperations.cls
/**
 * Created by dominikbarchanski on 04/07/2022.
 */

public with sharing class Aura_dmlOperations {
    @AuraEnabled
    public static void deleteAfterCancel (List<String> photoList ){
        delete [SELECT Id FROM ContentDocument WHERE Id IN :photoList ];
    }
//    @AuraEnabled
//    public static List<Object> getProducts(String name){
//        List<Id,Currency> priceList= new List<Id,Currency>( [SELECT Product2Id, UnitPrice FROM PricebookEntry]);
//        String soqlValue= '%'+ name +'%';
//        List<Product2> productList = [SELECT Id,Name,Family,Horsepower__c,Brands__c FROM Product2];
//        List<Object> retList = new List<Object>();
//        for (Product2 item: productList){
//
//        }
//    }
    @AuraEnabled
    public static String deleteDocuments(String docId) {
        try {
            delete [SELECT Id FROM ContentDocument WHERE Id = :docId];
            return 'SUCCESS';
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    class jsDataWrapper {
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String description;
        @AuraEnabled
        public Decimal price;
        @AuraEnabled
        public String mainPhoto;
        @AuraEnabled
        public List<String> photos;
        @AuraEnabled
        public String type;
        @AuraEnabled
        public Integer hp;
        @AuraEnabled
        public String brand;

        jsDataWrapper(Map<String, Object> jsObj) {
            this.name = (String) jsObj.get('name');
            this.mainPhoto = (String) jsObj.get('mainPhoto');
            this.description = (String) jsObj.get('description');
            this.price = Decimal.valueOf((String) jsObj.get('price'));
            this.type = (String) jsObj.get('type');
            this.hp = Integer.valueOf(jsObj.get('hp'));
            this.brand = (String) jsObj.get('brand');
            List<Object> photoList = (List<Object>) JSON.deserializeUntyped(
                    JSON.serialize(jsObj.get('photoList'))
            );
            List<String> newPhotoList = new List<String>();
            for (Object i : photoList) {
                newPhotoList.add(String.valueOf(i));
            }
            this.photos = newPhotoList;
        }

    }
    @AuraEnabled
    public static String insertProduct(Map<String, Object> jsObject) {

        jsDataWrapper recFromJs = new jsDataWrapper(jsObject);

        try {
            Product2 toAdd = new Product2();
            toAdd.Name = recFromJs.name;
            toAdd.Family = recFromJs.type;
            toAdd.Horsepower__c = recFromJs.hp;
            toAdd.Description = recFromJs.description;
            toAdd.Brands__c = recFromJs.brand;
            toAdd.Main_Photo__c = recFromJs.mainPhoto != null ? recFromJs.mainPhoto : null;
            toAdd.IsActive = true;

            insert toAdd;
            System.debug(toAdd.Id);
            if (recFromJs.photos != null) {
                if (recFromJs.photos.size() > 0) {
                    List<ContentVersion> photoRelatedToProduct = [SELECT Id, FirstPublishLocationId, Product__c FROM ContentVersion WHERE ContentDocumentId IN :recFromJs.photos];
                    for (ContentVersion item : photoRelatedToProduct) {
                        item.Product__c = toAdd.Id;
                    }
                    update photoRelatedToProduct;
                }
            }
            Pricebook2 pricebookId = [SELECT Id FROM Pricebook2 WHERE IsStandard = TRUE LIMIT 1];
            PricebookEntry newProd = new PricebookEntry();
            newProd.Pricebook2Id = pricebookId.Id;
            newProd.Product2Id = toAdd.Id;
            newProd.IsActive = true;
            newProd.UnitPrice = recFromJs.price;
            insert newProd;
            Strategy__c newItemInStrategy = new Strategy__c();
            newItemInStrategy.Product2id__c = toAdd.Id;
            newItemInStrategy.Standard_Price__c = recFromJs.price;
            newItemInStrategy.Strategy_price__c = recFromJs.price;
            newItemInStrategy.Strategy_Name__c = 'standard';
            insert newItemInStrategy;


            return null;
        } catch (Exception e) {
            System.debug(e);
            return 'ERROR';
        }
    }
    @AuraEnabled
    public static List<String> getBrands() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Product2.Brands__c.getDescribe();
        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p : pList) {
            options.add(p.getLabel());
        }
        return options;
    }

}