src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Average_Fuel_Consumption__c</fullName>
        <label>Average Fuel Consumption</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cylinder_Capacity__c</fullName>
        <label>Cylinder Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fuel_Consumption_In_The_City__c</fullName>
        <label>Fuel Consumption In The City</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Doors__c</fullName>
        <label>Number of Doors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Top_Speed__c</fullName>
        <label>Top Speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContentVersionHelperTest.cls
/**
 * Created by dominikbarchanski on 18/08/2022.
 */

@IsTest
private class ContentVersionHelperTest {
    @TestSetup
    private static void setupTestData() {
        Product2 prod1 = new Product2(Name = 'a', Fuel_Consumption_In_The_City__c = 1,
                Average_Fuel_Consumption__c = 1,
                Number_of_Doors__c = 1,
                Cylinder_Capacity__c = 1,
                Number_of_Places__c = 1,
                Top_Speed__c = 1
        );
        Product2 prod2 = new Product2(Name = 'a', Fuel_Consumption_In_The_City__c = 1,
                Average_Fuel_Consumption__c = 1,
                Number_of_Doors__c = 1,
                Cylinder_Capacity__c = 1,
                Number_of_Places__c = 1,
                Top_Speed__c = 1);
        insert prod1;
        insert prod2;
        ContentVersion content = new ContentVersion();
        content.Title = 'Title_Picture';
        content.FirstPublishLocationId = prod1.Id;
        content.PathOnClient = '/' + content.Title + '.jpg';
        Blob bodyBlob = Blob.valueOf('Test ContentVersion Body');
        content.VersionData = bodyBlob;
        insert content;
    }
    @IsTest
    static void testBehavior() {
        ContentVersionHelper.insertContentDistribution(new List<ContentVersion>{new ContentVersion()});
    }
    @IsTest
    static void testBehaviorOvverriade() {
        ContentVersion item = [
                SELECT
                        Checksum,
                        ContentBodyId,
                        ContentDocumentId,
                        ContentLocation,
                        ContentModifiedById,
                        ContentModifiedDate,
                        ContentSize,
                        ContentUrl,
                        CreatedById,
                        CreatedDate,
                        Description,
                        ExternalDataSourceId,
                        ExternalDocumentInfo1,
                        ExternalDocumentInfo2,
                        FeaturedContentBoost,
                        FeaturedContentDate,
                        FileExtension,
                        FileType,
                        FirstPublishLocationId,
                        Id,
                        IsAssetEnabled,
                        IsDeleted,
                        IsLatest,
                        IsMajorVersion,
                        LastModifiedById,
                        LastModifiedDate,
                        NegativeRatingCount,
                        NetworkId,
                        Origin,
                        OwnerId,
                        PathOnClient,
                        PositiveRatingCount,
                        Product__c,
                        PublishStatus,
                        RatingCount,
                        ReasonForChange,
                        SharingOption,
                        SharingPrivacy,
                        SystemModstamp,
                        TagCsv,
                        TextPreview,
                        Title,
                        VersionData,
                        VersionNumber
                FROM ContentVersion LIMIT 1];
        item.Title ='test';
        update item;

    }
}