src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryH</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TriggerProcess__c</fullName>
        <defaultValue>true</defaultValue>
        <label>TriggerProcess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>externalId__c</fullName>
        <externalId>true</externalId>
        <label>externalId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paramId__c</fullName>
        <label>paramId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/REST_MapObject.cls
/**
 * Created by dominikbarchanski on 21/05/2022.
 */

global with sharing class REST_MapObject {

    global static Hospital__c mapToHospitalFromDTO(REST_HospitalDTO hospitalDTO) {
//        List<Hospital__c> mappedHospital;
        Hospital__c hospitalToList = new Hospital__c();
//        for (REST_HospitalDTO item:hospitalDTO) {
//        if (String.isNotBlank(hospitalDTO.hospitalExternalId)) {
//
//        }else{
//
//        }
//        hospitalToList.externalId__c = hospitalDTO.hospitalExternalId;
        hospitalToList.externalId__c = hospitalDTO.hospitalExternalId;
        hospitalToList.Id = hospitalDTO.hospitalId;
        hospitalToList.Name = hospitalDTO.hospitalName;
        hospitalToList.Phone__c = hospitalDTO.hospitalPhone;
        hospitalToList.Email__c = hospitalDTO.hospitalEmail;
        hospitalToList.Country__c = hospitalDTO.hospitalCountry;
        hospitalToList.City__c = hospitalDTO.hospitalCity;
        hospitalToList.Street__c = hospitalDTO.hospitalStreet;
//        System.debug()
        if (hospitalDTO.hospitalCheckBox != true) {
            hospitalToList.TriggerProcess__c = false;
        }else {
            hospitalToList.TriggerProcess__c = true;
        }
//            mappedHospital.add(hospitalToList);
//        }
        return hospitalToList;

    }
    global static Hospital__c mapToHospitalFromDTOnId(REST_HospitalDTO hospitalDTO) {
//        List<Hospital__c> mappedHospital;
        Hospital__c hospitalToList = new Hospital__c();
//        for (REST_HospitalDTO item:hospitalDTO) {
        hospitalToList.paramId__c = hospitalDTO.hospitalId;
        hospitalToList.externalId__c=hospitalDTO.hospitalExternalId;
        hospitalToList.TriggerProcess__c = hospitalDTO.hospitalCheckBox;
        hospitalToList.Name = hospitalDTO.hospitalName;
        hospitalToList.Phone__c = hospitalDTO.hospitalPhone;
        hospitalToList.Email__c = hospitalDTO.hospitalEmail;
        hospitalToList.Country__c = hospitalDTO.hospitalCountry;
        hospitalToList.City__c = hospitalDTO.hospitalCity;
        hospitalToList.Street__c = hospitalDTO.hospitalStreet;
//            mappedHospital.add(hospitalToList);
//        }
        return hospitalToList;

    }


}