src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryH</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TriggerProcess__c</fullName>
        <defaultValue>true</defaultValue>
        <label>TriggerProcess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>externalId__c</fullName>
        <externalId>true</externalId>
        <label>externalId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paramId__c</fullName>
        <label>paramId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/REST_HospitalDTO.cls
/**
 * Created by dominikbarchanski on 21/05/2022.
 */

global with sharing class REST_HospitalDTO {
    global String hospitalId;
    global String hospitalExternalId;
    global String hospitalName;
    global String hospitalPhone;
    global String hospitalEmail;
    global String hospitalCountry;
    global String hospitalCity;
    global String hospitalStreet;
    global String paramId;
    global Boolean hospitalCheckBox;
    global REST_HospitalDTO(Hospital__c hospital) {
        Boolean boolState;
        if(hospital.TriggerProcess__c != true){
            boolState = false;
        }else{
            boolState = true;
        }
        this.hospitalCheckBox = boolState;
        this.hospitalExternalId = hospital.externalId__c;
        this.paramId = hospital.paramId__c;
        this.hospitalId = hospital.Id;
        this.hospitalName = hospital.Name;
        this.hospitalPhone = hospital.Phone__c;
        this.hospitalEmail = hospital.Email__c;
        this.hospitalCountry = hospital.Country__c;
        this.hospitalCity = hospital.City__c;
        this.hospitalStreet = hospital.Street__c;
    }
}