src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Average_Fuel_Consumption__c</fullName>
        <label>Average Fuel Consumption</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <label>Brands</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>carBrand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cylinder_Capacity__c</fullName>
        <label>Cylinder Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fuel_Consumption_In_The_City__c</fullName>
        <label>Fuel Consumption In The City</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Horsepower__c</fullName>
        <label>Horsepower</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Photo__c</fullName>
        <label>Main Photo</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Doors__c</fullName>
        <label>Number of Doors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_Year__c</fullName>
        <label>Production Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Speed__c</fullName>
        <label>Top Speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shopping_Cart__c.object
<CustomObject>
    <fields>
        <fullName>Product_Id__c</fullName>
        <label>Product Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <label>User Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping Cart</label>
    <nameField>
        <label>Shopping Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategy__c.object
<CustomObject>
    <fields>
        <fullName>Product2id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product2id</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Strategys</relationshipLabel>
        <relationshipName>Strategys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LWC_dmlOperationTest.cls
/**
 * Created by dominikbarchanski on 19/08/2022.
 */

@IsTest
private class LWC_dmlOperationTest implements HttpCalloutMock {
    @TestSetup
    private static void setupTestData() {
        Pricebook2 standartPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                IsActive = true);
        update standartPricebook;
        Pricebook2 pricebookins = new Pricebook2(
                Name = 'a',
                IsActive = true,
                End_date__c = Date.today(),
                Start_Date__c = Date.today()
        );
        insert pricebookins;
        Product2 prod1 = new Product2(Name = 'a',Fuel_Consumption_In_The_City__c=1,
                Average_Fuel_Consumption__c=1,
                Number_of_Doors__c=1,
                Cylinder_Capacity__c=1,
                Number_of_Places__c=1,
                Top_Speed__c=1
                );
        Product2 prod2 = new Product2(Name = 'a',Fuel_Consumption_In_The_City__c=1,
                Average_Fuel_Consumption__c=1,
                Number_of_Doors__c=1,
                Cylinder_Capacity__c=1,
                Number_of_Places__c=1,
                Top_Speed__c=1);
        insert prod1;
        insert prod2;
        Shopping_Cart__c itemcCart1 = new Shopping_Cart__c(
                Product_Id__c = prod1.Id,
                User_Id__c = 'a');
        insert itemcCart1;
        PricebookEntry entry = new PricebookEntry(
                UnitPrice = 500,
                Product2Id = prod1.Id,
                Pricebook2Id = standartPricebook.Id,
                IsActive = true
        );
        insert entry;
        Strategy__c start = new Strategy__c(
                Standard_Price__c = 100,
                Product2id__c = prod1.Id
        );
        Strategy__c start2 = new Strategy__c(
                Standard_Price__c = 100,
                Product2id__c = prod2.Id
        );
        Shopping_Cart__c itemcCart = new Shopping_Cart__c(Product_Id__c = 'a', User_Id__c = 'a');
        insert itemcCart;
        insert start;
        insert start2;
        ContentVersion content = new ContentVersion();
        ContentVersion content1 = new ContentVersion();
        content.Title = 'Title_Picture';
        content.FirstPublishLocationId = prod1.Id;
        content.PathOnClient = '/' + content.Title + '.jpg';
        Blob bodyBlob = Blob.valueOf('Test ContentVersion Body');
        content.VersionData = bodyBlob;
        insert content;
        content1.Title = 'Title_Picture';
        content1.FirstPublishLocationId = prod1.Id;
        content1.PathOnClient = '/' + content.Title + '.jpg';
        content1.VersionData = bodyBlob;
        insert content1;
        ContentDistribution itemCD = new ContentDistribution(
                ContentVersionId = content.Id,
                Name = content.Id
        );
        ContentDistribution itemCD1 = new ContentDistribution(
                ContentVersionId = content1.Id,
                Name = content1.Id
        );
        insert itemCD1;
        insert itemCD;
    }
    @IsTest
    static void allPricebookTest() {
        Test.startTest();
        LWC_dmlOperation.getAllPricebookItems();
        Test.stopTest();
    }
    @IsTest
    static void getCVTest() {
        Test.startTest();
        LWC_dmlOperation.getAllContentVersion();
        Test.stopTest();
    }
    @IsTest
    static void getCDTest() {
        Test.startTest();
        LWC_dmlOperation.getAllContentDistribution();
        Test.stopTest();
    }
    @IsTest
    static void getAllProdTest() {
        Test.startTest();
        LWC_dmlOperation.getAllProducts('a');
        Test.stopTest();
    }
    @IsTest
    static void searchProdProdTest() {
        Test.startTest();
        LWC_dmlOperation.searchProduct('a');
        Test.stopTest();
    }
    @IsTest
    static void getSingleProdTest() {
        LWC_dmlOperation.getSingleProduct([SELECT Id FROM Product2 LIMIT 1].Id, 'a');
    }
    @IsTest
    static void addComment() {
        LWC_dmlOperation.AddCommentAndRate('', 'a', [SELECT Id FROM Product2 LIMIT 1].Id, 1, 'a', 'a', 1, 1, 1);
    }
    @IsTest
    static void removeComment() {
        LWC_dmlOperation.removeAddedComment('', [SELECT Id FROM Product2 LIMIT 1].Id);
    }
    @IsTest
    static void addtoCart() {
        Map<String, Object> cart = new Map<String, Object>();
        cart.put('userId', 'a');
        cart.put('prodId', 'a');
        LWC_dmlOperation.addProductToCart(cart);
    }
    @IsTest
    static void allprodFromcart() {
        Map<String, Object> cart = new Map<String, Object>();
        cart.put('userId', 'a');
        cart.put('prodId', 'a');
        LWC_dmlOperation.addProductToCart(cart);
        LWC_dmlOperation.allProductsFormCart('a');
    }
    @IsTest
    static void displayCart() {
        LWC_dmlOperation.displayProductToBuy([SELECT Id FROM Product2 LIMIT 1].Id);
    }
    @IsTest
    static void deleteCart() {
        LWC_dmlOperation.displayProductToBuy([SELECT Id FROM Shopping_Cart__c LIMIT 1].Id);
    }
    public HttpResponse respond(HttpRequest param1) {
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('{"results":[{"address_components":[{"long_name":"Katowice","short_name":"Katowice","types":["locality","political"]},{"long_name":"Katowice","short_name":"Katowice","types":["administrative_area_level_2","political"]},{"long_name":"Śląskie","short_name":"Śląskie","types":["administrative_area_level_1","political"]},{"long_name":"Polska","short_name":"PL","types":["country","political"]},{"long_name":"40","short_name":"40","types":["postal_code","postal_code_prefix"]}],"formatted_address":"Katowice, Polska","geometry":{"bounds":{"northeast":{"lat":50.2973176,"lng":19.122919},"southwest":{"lat":50.1300272,"lng":18.8914664}},"location":{"lat":50.26489189999999,"lng":19.0237815},"location_type":"APPROXIMATE","viewport":{"northeast":{"lat":50.2973176,"lng":19.122919},"southwest":{"lat":50.1300272,"lng":18.8914664}}},"place_id":"ChIJ0cyhNiPOFkcRu_pZBTUqr7k","types":["locality","political"]}],"status":"OK"}');
        response.setStatusCode(200);
        return response;
    }
    @IsTest
    static void apiCart() {
        Product2 item = [
                SELECT
                        Average_Fuel_Consumption__c,
                        Brands__c,
                        City__c,
                        Country__c,
                        CreatedById,
                        CreatedDate,
                        Cylinder_Capacity__c,
                        Description,
                        DisplayUrl,
                        ExternalDataSourceId,
                        ExternalId,
                        Family,
                        Fuel_Consumption_In_The_City__c,
                        Horsepower__c,
                        Id,
                        IsActive,
                        IsArchived,
                        IsDeleted,
                        LastModifiedById,
                        LastModifiedDate,
                        LastReferencedDate,
                        LastViewedDate,
                        Latitude__c,
                        Longitude__c,
                        Main_Photo__c,
                        Name,
                        Number_of_Doors__c,
                        Number_of_Places__c,
                        ProductCode,
                        Production_Year__c,
                        QuantityUnitOfMeasure,
                        StockKeepingUnit,
                        Street__c,
                        SystemModstamp,
                        Top_Speed__c
                FROM Product2
                LIMIT 1
        ];
        LWC_dmlOperation.apiCall(item);
        LWC_dmlOperation.apiCall(null);
    }


}