src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Average_Fuel_Consumption__c</fullName>
        <label>Average Fuel Consumption</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cylinder_Capacity__c</fullName>
        <label>Cylinder Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fuel_Consumption_In_The_City__c</fullName>
        <label>Fuel Consumption In The City</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Doors__c</fullName>
        <label>Number of Doors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Top_Speed__c</fullName>
        <label>Top Speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testBatch.cls
/**
 * Created by dominikbarchanski on 19/08/2022.
 */

@IsTest
private class testBatch {
    @TestSetup
    static void testStetum(){
        Pricebook2 standartPricebook = new Pricebook2(
                Id=Test.getStandardPricebookId(),
                IsActive=true);
        update  standartPricebook;
    }
    @IsTest
    static void testBehavior() {
        SCS_PricebookBatch scs = new SCS_PricebookBatch();
        Database.executeBatch(scs);
    }
    @IsTest
    static void testtrigger(){
        Product2 prod1 = new Product2(Name = 'a',Fuel_Consumption_In_The_City__c=1,
                Average_Fuel_Consumption__c=1,
                Number_of_Doors__c=1,
                Cylinder_Capacity__c=1,
                Number_of_Places__c=1,
                Top_Speed__c=1);
        insert prod1;
        ContentVersion content = new ContentVersion();

        content.Title = 'Title_Picture';
        content.FirstPublishLocationId = prod1.Id;
        content.PathOnClient = '/' + content.Title + '.jpg';
        Blob bodyBlob = Blob.valueOf('Test ContentVersion Body');
        content.VersionData = bodyBlob;
        insert content;
    }
    @IsTest
    static void exequtetest(){
        Test.startTest();
        String jobId = System.schedule('testBasicScheduledApex', '0 0 0 3 9 ? 2022', new schedulePromotions());
        Test.stopTest();
    }
}